### ISSUE TITLE
parse markdown in contenteditable

### ISSUE THREAD

**Issue by dzfranklin** [tuvistavie/atomic-chrome#13]
Often in contentediable based editors the controls offered are too limited or are annoying to use, so a method to type in them using markdown would be very useful. If the text typed in Atom was run through a  markdown to html converter before being sent to a contentediable that would be very convenient. Is this possible as a setting?

Thanks,
Daniel

**Comment by danhper** [comment]
Hi, thank you for the suggestion.
The feature has already beek asked in #4. 
It is possible, but not as trivial as it seems:
because as the text is synchonized, we need
to have something that converts both ways without loosing information (as much as markdown allows us to).
I started a bit the work in https://github.com/tuvistavie/meditable, but did not really have the time to work on it recently, so help is very welcome.
As This issue is basically the same as #4, I will close here.
Thank you!
